
Running tests... 
----------------------------------------------------------------------
 test_game_controls (GameTest.GameTest.test_game_controls) ... OK (10.389548)s
 test_game_score (GameTest.GameTest.test_game_score) ... OK (16.678779)s
 test_start_game (GameTest.GameTest.test_start_game) ... OK (7.146775)s
 test_verify_garbage_collector_color (GameTest.GameTest.test_verify_garbage_collector_color) ... OK (6.246699)s
 test_versus_gameplay (GameTest.GameTest.test_versus_gameplay) ... ERROR (18.378580)s
 test_leaderboard_update (UpdateTest.UpdateTest.test_leaderboard_update) ... OK (33.871677)s
 test_watch_realtime (UpdateTest.UpdateTest.test_watch_realtime) ... OK (12.588558)s
 test_account_creation (UserAccountTest.UserAccountTest.test_account_creation) ... OK (5.081629)s
 test_account_login (UserAccountTest.UserAccountTest.test_account_login) ... OK (4.540929)s
 test_account_logout (UserAccountTest.UserAccountTest.test_account_logout) ... OK (4.938968)s
 test_click_specific_color (UserAccountTest.UserAccountTest.test_click_specific_color) ... OK (5.932389)s
 test_send_message (UserAccountTest.UserAccountTest.test_send_message) ... ERROR (22.491266)s
 test_settings_and_play_with_movement (UserAccountTest.UserAccountTest.test_settings_and_play_with_movement) ... OK (9.374706)s

======================================================================
ERROR [18.378580s]: GameTest.GameTest.test_versus_gameplay
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\laxjo\OneDrive\Desktop\Capstone\aldwairi-projects-danglingpointers\application\backend\test\GameTest.py", line 175, in test_versus_gameplay
    webdriverwait1.until(
  File "C:\Users\laxjo\OneDrive\Desktop\Capstone\aldwairi-projects-danglingpointers\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


======================================================================
ERROR [22.491266s]: UserAccountTest.UserAccountTest.test_send_message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\laxjo\OneDrive\Desktop\Capstone\aldwairi-projects-danglingpointers\application\backend\test\UserAccountTest.py", line 168, in test_send_message
    received_message = webdriverwait2.until(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laxjo\OneDrive\Desktop\Capstone\aldwairi-projects-danglingpointers\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF63BA46CF5+28821]
	(No symbol) [0x00007FF63B9B3880]
	(No symbol) [0x00007FF63B85578A]
	(No symbol) [0x00007FF63B8A91BE]
	(No symbol) [0x00007FF63B8A94AC]
	(No symbol) [0x00007FF63B8F2647]
	(No symbol) [0x00007FF63B8CF33F]
	(No symbol) [0x00007FF63B8EF412]
	(No symbol) [0x00007FF63B8CF0A3]
	(No symbol) [0x00007FF63B89A778]
	(No symbol) [0x00007FF63B89B8E1]
	GetHandleVerifier [0x00007FF63BD7FCED+3408013]
	GetHandleVerifier [0x00007FF63BD9745F+3504127]
	GetHandleVerifier [0x00007FF63BD8B63D+3455453]
	GetHandleVerifier [0x00007FF63BB0BDFB+835995]
	(No symbol) [0x00007FF63B9BEB9F]
	(No symbol) [0x00007FF63B9BA854]
	(No symbol) [0x00007FF63B9BA9ED]
	(No symbol) [0x00007FF63B9AA1D9]
	BaseThreadInitThunk [0x00007FFDEE58259D+29]
	RtlUserThreadStart [0x00007FFDEFECAF38+40]


----------------------------------------------------------------------
Ran 13 tests in 0:03:18

FAILED
 (Errors=2)

Generating HTML reports... 
reports\TestResults_GameTest_UpdateTest_UserAccountTest_2024-12-07_16-55-11.html
